// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var Block              = require("bs-platform/lib/js/block.js");
var Curry              = require("bs-platform/lib/js/curry.js");
var StyleRe            = require("bs-react-native/lib/js/src/styleRe.js");
var Components         = require("../components.js");
var ReactNative        = require("bs-react-native/lib/js/src/reactNative.js");
var ReasonReact        = require("reason-react/lib/js/src/reasonReact.js");
var StatusBarRe        = require("bs-react-native/lib/js/src/components/statusBarRe.js");
var StyleSheetRe       = require("bs-react-native/lib/js/src/styleSheetRe.js");
var TouchableOpacityRe = require("bs-react-native/lib/js/src/components/touchableOpacityRe.js");

var component = ReasonReact.statelessComponent("Home");

var stylesheet = StyleSheetRe.create({
      title: StyleRe.style(/* :: */[
            StyleRe.color("white"),
            /* [] */0
          ]),
      wrapper: StyleRe.style(/* :: */[
            StyleRe.widthPct(80.0),
            /* [] */0
          ]),
      jumboButton: StyleRe.style(/* :: */[
            StyleRe.borderWidth(3.0),
            /* :: */[
              StyleRe.borderColor("white"),
              /* [] */0
            ]
          ])
    });

function make(dispatch, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Curry._4(Components.Column[/* make */1], /* Some */[/* center */98248149], /* Some */[/* center */98248149], /* None */0, /* array */[
                      ReasonReact.element(/* None */0, /* None */0, StatusBarRe.make(/* None */0, /* Some */[/* lightContent */-106329341], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[])),
                      ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.BackgroundImage[/* make */1], /* Required */Block.__(1, [require("../../../../img/img-25-dark.jpg")]), /* None */0, /* array */[])),
                      ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* Some */[stylesheet.wrapper],
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* array */[
                                  ReasonReact.element(/* None */0, /* None */0, Curry._2(Components.Padding[/* make */1], /* None */0, /* array */[
                                            ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "K\xc3\xa6re kunde", /* None */0, /* array */[])),
                                            ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "Giv os lidt baggrundsviden s\xc3\xa5 vi bedre kan betj\xc3\xa6ne dig", /* None */0, /* array */[]))
                                          ])),
                                  ReasonReact.element(/* None */0, /* None */0, Curry._2(Components.Padding[/* make */1], /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, TouchableOpacityRe.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[(function () {
                                                            return Curry._1(dispatch, /* SelectVisitorType */Block.__(4, [/* Private */1]));
                                                          })], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, Curry._4(Components.Row[/* make */1], /* Some */[/* spaceBetween */516682146], /* Some */[/* center */98248149], /* Some */[stylesheet.jumboButton], /* array */[
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "1", /* None */0, /* array */[])),
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "Jeg er privat kunde og k\xc3\xb8ber eller leaser selv min n\xc3\xa6ste bil", /* None */0, /* array */[])),
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], ">", /* None */0, /* array */[]))
                                                              ]))]))])),
                                  ReasonReact.element(/* None */0, /* None */0, Curry._2(Components.Padding[/* make */1], /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, TouchableOpacityRe.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[(function () {
                                                            return Curry._1(dispatch, /* SelectVisitorType */Block.__(4, [/* PrivateToBusiness */2]));
                                                          })], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, Curry._4(Components.Row[/* make */1], /* Some */[/* spaceBetween */516682146], /* Some */[/* center */98248149], /* Some */[stylesheet.jumboButton], /* array */[
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "2", /* None */0, /* array */[])),
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "Jeg er privat kunde og skal skifte til firmabil", /* None */0, /* array */[])),
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], ">", /* None */0, /* array */[]))
                                                              ]))]))])),
                                  ReasonReact.element(/* None */0, /* None */0, Curry._2(Components.Padding[/* make */1], /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, TouchableOpacityRe.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[(function () {
                                                            return Curry._1(dispatch, /* SelectVisitorType */Block.__(4, [/* Business */3]));
                                                          })], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, Curry._4(Components.Row[/* make */1], /* Some */[/* spaceBetween */516682146], /* Some */[/* center */98248149], /* Some */[stylesheet.jumboButton], /* array */[
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "3", /* None */0, /* array */[])),
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "Jeg k\xc3\xb8rer firmabil og skal v\xc3\xa6lge min n\xc3\xa6ste firmabil", /* None */0, /* array */[])),
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], ">", /* None */0, /* array */[]))
                                                              ]))]))])),
                                  ReasonReact.element(/* None */0, /* None */0, Curry._2(Components.Padding[/* make */1], /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, TouchableOpacityRe.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[(function () {
                                                            return Curry._1(dispatch, /* SelectVisitorType */Block.__(4, [/* Na */4]));
                                                          })], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, Curry._4(Components.Row[/* make */1], /* Some */[/* spaceBetween */516682146], /* Some */[/* center */98248149], /* Some */[stylesheet.jumboButton], /* array */[
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "4", /* None */0, /* array */[])),
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "Jeg \xc3\xb8nsker ikke at dele denne information", /* None */0, /* array */[])),
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], ">", /* None */0, /* array */[]))
                                                              ]))]))])),
                                  ReasonReact.element(/* None */0, /* None */0, Curry._2(Components.Padding[/* make */1], /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, Curry._4(Components.Row[/* make */1], /* Some */[/* spaceBetween */516682146], /* Some */[/* center */98248149], /* Some */[stylesheet.jumboButton], /* array */[
                                                      ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "1", /* None */0, /* array */[])),
                                                      ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "Jeg er privat kunde og k\xc3\xb8ber eller leaser selv min n\xc3\xa6ste bil", /* None */0, /* array */[])),
                                                      ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], ">", /* None */0, /* array */[]))
                                                    ]))]))
                                ]
                              ]))
                    ]));
    });
  return newrecord;
}

exports.component  = component;
exports.stylesheet = stylesheet;
exports.make       = make;
/* component Not a pure module */
