// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var Block               = require("bs-platform/lib/js/block.js");
var Curry               = require("bs-platform/lib/js/curry.js");
var StyleRe             = require("bs-react-native/lib/js/src/styleRe.js");
var Components          = require("../components.js");
var ReactNative         = require("bs-react-native/lib/js/src/reactNative.js");
var ReasonReact         = require("reason-react/lib/js/src/reasonReact.js");
var StatusBarRe         = require("bs-react-native/lib/js/src/components/statusBarRe.js");
var ActivityIndicatorRe = require("bs-react-native/lib/js/src/components/activityIndicatorRe.js");

function setPasswordRef(theRef, _) {
  return /* SilentUpdate */Block.__(1, [/* record */[/* passwordRef */theRef === null ? /* None */0 : [theRef]]]);
}

var component = ReasonReact.statefulComponent("LoginPage");

function make(dispatch, loginForm, session, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      var submit = function () {
        return Curry._1(dispatch, /* Login */Block.__(1, [loginForm]));
      };
      var $js;
      $js = typeof session === "number" ? (
          session ? ReasonReact.element(/* None */0, /* None */0, ActivityIndicatorRe.make(/* None */0, /* None */0, /* Some */[/* large */-272944197], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[])) : null
        ) : (
          session.tag ? null : ReasonReact.element(/* None */0, /* None */0, Curry._4(Components.Alert[/* make */1], /* None */0, /* Some */[/* danger */512905955], session[0], /* array */[]))
        );
      return ReasonReact.element(/* None */0, /* None */0, Curry._4(Components.Column[/* make */1], /* Some */[/* center */98248149], /* Some */[/* center */98248149], /* None */0, /* array */[
                      ReasonReact.element(/* None */0, /* None */0, StatusBarRe.make(/* None */0, /* Some */[/* lightContent */-106329341], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[])),
                      ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.BackgroundImage[/* make */1], /* Required */Block.__(1, [require("../../../../img/img-25-dark.jpg")]), /* None */0, /* array */[])),
                      ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* Some */[StyleRe.style(/* :: */[
                                        StyleRe.widthPct(80.0),
                                        /* [] */0
                                      ])],
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* array */[
                                  ReasonReact.element(/* None */0, /* None */0, Curry._2(Components.InputGroup[/* make */1], /* None */0, /* array */[
                                            ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Label[/* make */1], "Email", /* None */0, /* array */[])),
                                            ReasonReact.element(/* None */0, /* None */0, Curry.app(Components.Input[/* make */1], [
                                                      /* None */0,
                                                      /* Some */[/* none */-922086728],
                                                      /* None */0,
                                                      /* Some */[/* emailAddress */1008346616],
                                                      /* None */0,
                                                      (function (email) {
                                                          return Curry._1(dispatch, /* UpdateLoginForm */Block.__(0, [/* record */[
                                                                          /* email */email,
                                                                          /* password */loginForm[/* password */1]
                                                                        ]]));
                                                        }),
                                                      /* Some */[(function () {
                                                            var ref = self[/* state */3][/* passwordRef */0];
                                                            if (ref) {
                                                              return ref[0].focus();
                                                            } else {
                                                              return /* () */0;
                                                            }
                                                          })],
                                                      /* None */0,
                                                      loginForm[/* email */0],
                                                      /* array */[]
                                                    ]))
                                          ])),
                                  ReasonReact.element(/* None */0, /* None */0, Curry._2(Components.InputGroup[/* make */1], /* None */0, /* array */[
                                            ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Label[/* make */1], "Password", /* None */0, /* array */[])),
                                            ReasonReact.element(/* None */0, /* None */0, Curry.app(Components.Input[/* make */1], [
                                                      /* Some */[Curry._1(self[/* update */2], setPasswordRef)],
                                                      /* Some */[/* none */-922086728],
                                                      /* None */0,
                                                      /* Some */[/* default */465819841],
                                                      /* Some */[/* true */1],
                                                      (function (password) {
                                                          return Curry._1(dispatch, /* UpdateLoginForm */Block.__(0, [/* record */[
                                                                          /* email */loginForm[/* email */0],
                                                                          /* password */password
                                                                        ]]));
                                                        }),
                                                      /* Some */[submit],
                                                      /* None */0,
                                                      loginForm[/* password */1],
                                                      /* array */[]
                                                    ]))
                                          ])),
                                  ReasonReact.element(/* None */0, /* None */0, Curry._4(Components.Btn[/* make */1], /* None */0, submit, /* Some */[/* success */944645571], /* array */[ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "Go", /* Some */[StyleRe.style(/* :: */[
                                                            StyleRe.color("white"),
                                                            /* [] */0
                                                          ])], /* array */[]))]))
                                ]
                              ])),
                      ReasonReact.element(/* None */0, /* None */0, Curry._2(Components.Padding[/* make */1], /* None */0, /* array */[$js]))
                    ]));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* passwordRef : None */0];
    });
  return newrecord;
}

exports.setPasswordRef = setPasswordRef;
exports.component      = component;
exports.make           = make;
/* component Not a pure module */
