// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var Block        = require("bs-platform/lib/js/block.js");
var Curry        = require("bs-platform/lib/js/curry.js");
var StyleRe      = require("bs-react-native/lib/js/src/styleRe.js");
var Components   = require("../components.js");
var ReactNative  = require("bs-react-native/lib/js/src/reactNative.js");
var ReasonReact  = require("reason-react/lib/js/src/reasonReact.js");
var StatusBarRe  = require("bs-react-native/lib/js/src/components/statusBarRe.js");
var StyleSheetRe = require("bs-react-native/lib/js/src/styleSheetRe.js");

var component = ReasonReact.statelessComponent("ThankYou");

var stylesheet = StyleSheetRe.create({
      title: StyleRe.style(/* :: */[
            StyleRe.color("white"),
            /* [] */0
          ]),
      wrapper: StyleRe.style(/* :: */[
            StyleRe.widthPct(80.0),
            /* [] */0
          ]),
      jumboButton: StyleRe.style(/* :: */[
            StyleRe.borderWidth(3.0),
            /* :: */[
              StyleRe.borderColor("white"),
              /* [] */0
            ]
          ])
    });

function make(_, _$1) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Curry._4(Components.Column[/* make */1], /* Some */[/* center */98248149], /* Some */[/* center */98248149], /* None */0, /* array */[
                      ReasonReact.element(/* None */0, /* None */0, StatusBarRe.make(/* None */0, /* Some */[/* lightContent */-106329341], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[])),
                      ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.BackgroundImage[/* make */1], /* Required */Block.__(1, [require("../../../../img/img-25-dark.jpg")]), /* None */0, /* array */[])),
                      ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* Some */[stylesheet.wrapper],
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* array */[ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "thank you", /* None */0, /* array */[]))]
                              ]))
                    ]));
    });
  return newrecord;
}

exports.component  = component;
exports.stylesheet = stylesheet;
exports.make       = make;
/* component Not a pure module */
