// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var Block              = require("bs-platform/lib/js/block.js");
var Curry              = require("bs-platform/lib/js/curry.js");
var StyleRe            = require("bs-react-native/lib/js/src/styleRe.js");
var Components         = require("../components.js");
var ReactNative        = require("bs-react-native/lib/js/src/reactNative.js");
var ReasonReact        = require("reason-react/lib/js/src/reasonReact.js");
var StatusBarRe        = require("bs-react-native/lib/js/src/components/statusBarRe.js");
var StyleSheetRe       = require("bs-react-native/lib/js/src/styleSheetRe.js");
var TouchableOpacityRe = require("bs-react-native/lib/js/src/components/touchableOpacityRe.js");

var component = ReasonReact.statelessComponent("VisitorInterests");

var stylesheet = StyleSheetRe.create({
      title: StyleRe.style(/* :: */[
            StyleRe.color("white"),
            /* [] */0
          ]),
      wrapper: StyleRe.style(/* :: */[
            StyleRe.widthPct(80.0),
            /* [] */0
          ]),
      jumboButton: StyleRe.style(/* :: */[
            StyleRe.borderWidth(3.0),
            /* :: */[
              StyleRe.borderColor("white"),
              /* [] */0
            ]
          ])
    });

function make(dispatch, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Curry._4(Components.Column[/* make */1], /* Some */[/* center */98248149], /* Some */[/* center */98248149], /* None */0, /* array */[
                      ReasonReact.element(/* None */0, /* None */0, StatusBarRe.make(/* None */0, /* Some */[/* lightContent */-106329341], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[])),
                      ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.BackgroundImage[/* make */1], /* Required */Block.__(1, [require("../../../../img/img-25-dark.jpg")]), /* None */0, /* array */[])),
                      ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* Some */[stylesheet.wrapper],
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* array */[
                                  ReasonReact.element(/* None */0, /* None */0, Curry._2(Components.Padding[/* make */1], /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "Da vores s\xc3\xa6lgere ofte er optaget, kan du v\xc3\xa6lge at f\xc3\xa5 hj\xc3\xa6lp af andet personale til for eksempel en pr\xc3\xb8vek\xc3\xb8rsel. \n            V\xc3\xa6lg den af de f\xc3\xb8lgende muligheder der bedst passer til dit form\xc3\xa5l med bes\xc3\xb8get hos os.", /* None */0, /* array */[]))])),
                                  ReasonReact.element(/* None */0, /* None */0, Curry._2(Components.Padding[/* make */1], /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, TouchableOpacityRe.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[(function () {
                                                            return Curry._1(dispatch, /* SelectVisitorInterests */Block.__(5, [/* Browsing */1]));
                                                          })], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, Curry._4(Components.Row[/* make */1], /* Some */[/* spaceBetween */516682146], /* Some */[/* center */98248149], /* Some */[stylesheet.jumboButton], /* array */[
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "A", /* None */0, /* array */[])),
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "Se og r\xc3\xb8re", /* None */0, /* array */[])),
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], ">", /* None */0, /* array */[]))
                                                              ]))]))])),
                                  ReasonReact.element(/* None */0, /* None */0, Curry._2(Components.Padding[/* make */1], /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, TouchableOpacityRe.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[(function () {
                                                            return Curry._1(dispatch, /* SelectVisitorInterests */Block.__(5, [/* Learn */2]));
                                                          })], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, Curry._4(Components.Row[/* make */1], /* Some */[/* spaceBetween */516682146], /* Some */[/* center */98248149], /* Some */[stylesheet.jumboButton], /* array */[
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "B", /* None */0, /* array */[])),
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "L\xc3\xa6re mere", /* None */0, /* array */[])),
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], ">", /* None */0, /* array */[]))
                                                              ]))]))])),
                                  ReasonReact.element(/* None */0, /* None */0, Curry._2(Components.Padding[/* make */1], /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, TouchableOpacityRe.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[(function () {
                                                            return Curry._1(dispatch, /* SelectVisitorInterests */Block.__(5, [/* Testdrive */3]));
                                                          })], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, Curry._4(Components.Row[/* make */1], /* Some */[/* spaceBetween */516682146], /* Some */[/* center */98248149], /* Some */[stylesheet.jumboButton], /* array */[
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "C", /* None */0, /* array */[])),
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "Pr\xc3\xb8vetur", /* None */0, /* array */[])),
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], ">", /* None */0, /* array */[]))
                                                              ]))]))])),
                                  ReasonReact.element(/* None */0, /* None */0, Curry._2(Components.Padding[/* make */1], /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, TouchableOpacityRe.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[(function () {
                                                            return Curry._1(dispatch, /* SelectVisitorInterests */Block.__(5, [/* Financing */4]));
                                                          })], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, Curry._4(Components.Row[/* make */1], /* Some */[/* spaceBetween */516682146], /* Some */[/* center */98248149], /* Some */[stylesheet.jumboButton], /* array */[
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "D", /* None */0, /* array */[])),
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "Financiering", /* None */0, /* array */[])),
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], ">", /* None */0, /* array */[]))
                                                              ]))]))])),
                                  ReasonReact.element(/* None */0, /* None */0, Curry._2(Components.Padding[/* make */1], /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, TouchableOpacityRe.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[(function () {
                                                            return Curry._1(dispatch, /* SelectVisitorInterests */Block.__(5, [/* Buy */5]));
                                                          })], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, Curry._4(Components.Row[/* make */1], /* Some */[/* spaceBetween */516682146], /* Some */[/* center */98248149], /* Some */[stylesheet.jumboButton], /* array */[
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "E", /* None */0, /* array */[])),
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "K\xc3\xb8be", /* None */0, /* array */[])),
                                                                ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], ">", /* None */0, /* array */[]))
                                                              ]))]))]))
                                ]
                              ]))
                    ]));
    });
  return newrecord;
}

exports.component  = component;
exports.stylesheet = stylesheet;
exports.make       = make;
/* component Not a pure module */
