// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var Block       = require("bs-platform/lib/js/block.js");
var Curry       = require("bs-platform/lib/js/curry.js");
var StyleRe     = require("bs-react-native/lib/js/src/styleRe.js");
var Components  = require("../components.js");
var ReactNative = require("bs-react-native/lib/js/src/reactNative.js");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");
var StatusBarRe = require("bs-react-native/lib/js/src/components/statusBarRe.js");

function setMobileRef(theRef, param) {
  return /* SilentUpdate */Block.__(1, [/* record */[
              /* mobileRef */theRef === null ? /* None */0 : [theRef],
              /* concentRef */param[/* state */3][/* concentRef */1]
            ]]);
}

function setConcnetRef(theRef, param) {
  return /* SilentUpdate */Block.__(1, [/* record */[
              /* mobileRef */param[/* state */3][/* mobileRef */0],
              /* concentRef */theRef === null ? /* None */0 : [theRef]
            ]]);
}

var component = ReasonReact.statefulComponent("VisitorDetailsPage");

function make(dispatch, visitorForm, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      var submit = function () {
        return Curry._1(dispatch, /* SubmitVisitorForm */Block.__(7, [visitorForm]));
      };
      return ReasonReact.element(/* None */0, /* None */0, Curry._4(Components.Column[/* make */1], /* Some */[/* center */98248149], /* Some */[/* center */98248149], /* None */0, /* array */[
                      ReasonReact.element(/* None */0, /* None */0, StatusBarRe.make(/* None */0, /* Some */[/* lightContent */-106329341], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[])),
                      ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.BackgroundImage[/* make */1], /* Required */Block.__(1, [require("../../../../img/img-25-dark.jpg")]), /* None */0, /* array */[])),
                      ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* Some */[StyleRe.style(/* :: */[
                                        StyleRe.widthPct(80.0),
                                        /* [] */0
                                      ])],
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* array */[
                                  ReasonReact.element(/* None */0, /* None */0, Curry._2(Components.InputGroup[/* make */1], /* None */0, /* array */[
                                            ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Label[/* make */1], "Name", /* None */0, /* array */[])),
                                            ReasonReact.element(/* None */0, /* None */0, Curry.app(Components.Input[/* make */1], [
                                                      /* None */0,
                                                      /* Some */[/* none */-922086728],
                                                      /* None */0,
                                                      /* Some */[/* default */465819841],
                                                      /* None */0,
                                                      (function (name) {
                                                          return Curry._1(dispatch, /* UpdateVisitorForm */Block.__(6, [/* record */[
                                                                          /* visitorType */visitorForm[/* visitorType */0],
                                                                          /* visitorInterests */visitorForm[/* visitorInterests */1],
                                                                          /* name */name,
                                                                          /* mobile */visitorForm[/* mobile */3],
                                                                          /* concent */visitorForm[/* concent */4]
                                                                        ]]));
                                                        }),
                                                      /* Some */[(function () {
                                                            var ref = self[/* state */3][/* mobileRef */0];
                                                            if (ref) {
                                                              return ref[0].focus();
                                                            } else {
                                                              return /* () */0;
                                                            }
                                                          })],
                                                      /* None */0,
                                                      visitorForm[/* name */2],
                                                      /* array */[]
                                                    ]))
                                          ])),
                                  ReasonReact.element(/* None */0, /* None */0, Curry._2(Components.InputGroup[/* make */1], /* None */0, /* array */[
                                            ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Label[/* make */1], "Mobile", /* None */0, /* array */[])),
                                            ReasonReact.element(/* None */0, /* None */0, Curry.app(Components.Input[/* make */1], [
                                                      /* Some */[Curry._1(self[/* update */2], setMobileRef)],
                                                      /* Some */[/* none */-922086728],
                                                      /* None */0,
                                                      /* Some */[/* decimalPad */965330242],
                                                      /* None */0,
                                                      (function (mobile) {
                                                          return Curry._1(dispatch, /* UpdateVisitorForm */Block.__(6, [/* record */[
                                                                          /* visitorType */visitorForm[/* visitorType */0],
                                                                          /* visitorInterests */visitorForm[/* visitorInterests */1],
                                                                          /* name */visitorForm[/* name */2],
                                                                          /* mobile */mobile,
                                                                          /* concent */visitorForm[/* concent */4]
                                                                        ]]));
                                                        }),
                                                      /* Some */[submit],
                                                      /* None */0,
                                                      visitorForm[/* mobile */3],
                                                      /* array */[]
                                                    ]))
                                          ])),
                                  ReasonReact.element(/* None */0, /* None */0, Curry._4(Components.Btn[/* make */1], /* None */0, submit, /* Some */[/* success */944645571], /* array */[ReasonReact.element(/* None */0, /* None */0, Curry._3(Components.Text[/* make */1], "S\xc3\xa6t mig i k\xc3\xb8", /* Some */[StyleRe.style(/* :: */[
                                                            StyleRe.color("white"),
                                                            /* [] */0
                                                          ])], /* array */[]))]))
                                ]
                              ]))
                    ]));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[
              /* mobileRef : None */0,
              /* concentRef : None */0
            ];
    });
  return newrecord;
}

exports.setMobileRef  = setMobileRef;
exports.setConcnetRef = setConcnetRef;
exports.component     = component;
exports.make          = make;
/* component Not a pure module */
