// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var Task           = require("./task.js");
var AsyncStorageRe = require("bs-react-native/lib/js/src/asyncStorageRe.js");

function setItem(key, value) {
  return Task.fromLazyPromise((function () {
                return AsyncStorageRe.setItem(key, value, /* None */0, /* () */0);
              }));
}

function getItem(key) {
  return Task.fromLazyPromise((function () {
                return AsyncStorageRe.getItem(key, /* None */0, /* () */0);
              }));
}

exports.setItem = setItem;
exports.getItem = getItem;
/* AsyncStorageRe Not a pure module */
