// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var Curry              = require("bs-platform/lib/js/curry.js");
var Theme              = require("./theme.js");
var TextRe             = require("bs-react-native/lib/js/src/components/textRe.js");
var ImageRe            = require("bs-react-native/lib/js/src/components/imageRe.js");
var StyleRe            = require("bs-react-native/lib/js/src/styleRe.js");
var PlatformRe         = require("bs-react-native/lib/js/src/platformRe.js");
var ReactNative        = require("bs-react-native/lib/js/src/reactNative.js");
var ReasonReact        = require("reason-react/lib/js/src/reasonReact.js");
var TextInputRe        = require("bs-react-native/lib/js/src/components/textInputRe.js");
var StyleSheetRe       = require("bs-react-native/lib/js/src/styleSheetRe.js");
var TouchableOpacityRe = require("bs-react-native/lib/js/src/components/touchableOpacityRe.js");

var _style = StyleRe.style(/* [] */0);

function shadow(i) {
  if (PlatformRe.os !== 0) {
    return /* :: */[
            StyleRe.elevation(i),
            /* [] */0
          ];
  } else {
    return /* :: */[
            StyleRe.shadowOffset(0.0, 0.7 * i),
            /* :: */[
              StyleRe.shadowRadius(0.7 * i),
              /* :: */[
                StyleRe.shadowColor("black"),
                /* :: */[
                  StyleRe.shadowOpacity(0.3),
                  /* [] */0
                ]
              ]
            ]
          ];
  }
}

var stylesheet = StyleSheetRe.create({
      text: StyleRe.style(/* :: */[
            StyleRe.fontSize(15.0),
            /* :: */[
              StyleRe.color("white"),
              /* :: */[
                StyleRe.backgroundColor("transparent"),
                /* [] */0
              ]
            ]
          ]),
      button: StyleRe.style(/* :: */[
            StyleRe.borderColor("#f0f0f0"),
            /* :: */[
              StyleRe.borderWidth(1.0),
              /* :: */[
                StyleRe.borderRadius(3.0),
                /* :: */[
                  StyleRe.padding(10.0),
                  /* :: */[
                    StyleRe.backgroundColor("transparent"),
                    /* :: */[
                      StyleRe.alignItems(/* center */98248149),
                      /* :: */[
                        StyleRe.justifyContent(/* center */98248149),
                        shadow(5.0)
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]),
      buttonSuccess: StyleRe.style(/* :: */[
            StyleRe.backgroundColor(Theme.success),
            /* :: */[
              StyleRe.borderColor("transparent"),
              /* [] */0
            ]
          ]),
      label: StyleRe.style(/* :: */[
            StyleRe.fontSize(15.0),
            /* :: */[
              StyleRe.color(Theme.success),
              /* :: */[
                StyleRe.backgroundColor("transparent"),
                /* [] */0
              ]
            ]
          ]),
      textInput: StyleRe.style(/* :: */[
            StyleRe.backgroundColor("transparent"),
            /* :: */[
              StyleRe.borderWidth(0.0),
              /* :: */[
                StyleRe.height(28.0),
                /* :: */[
                  StyleRe.padding(0.0),
                  /* :: */[
                    StyleRe.color("white"),
                    /* :: */[
                      StyleRe.fontSize(15.0),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]),
      textInputWrap: StyleRe.style(/* :: */[
            StyleRe.borderColor("#f0f0f0"),
            /* :: */[
              StyleRe.borderBottomWidth(1.0),
              /* [] */0
            ]
          ]),
      inputGroup: StyleRe.style(/* :: */[
            StyleRe.marginBottom(15.0),
            /* [] */0
          ]),
      row: StyleRe.style(/* :: */[
            StyleRe.flexDirection(/* row */5693978),
            /* :: */[
              StyleRe.flexGrow(1.0),
              /* [] */0
            ]
          ]),
      column: StyleRe.style(/* :: */[
            StyleRe.flexDirection(/* column */-963948842),
            /* :: */[
              StyleRe.flexGrow(1.0),
              /* [] */0
            ]
          ]),
      padding: StyleRe.style(/* :: */[
            StyleRe.padding(15.0),
            /* [] */0
          ]),
      backgroundImage: StyleRe.style(/* :: */[
            StyleRe.left(0.0),
            /* :: */[
              StyleRe.top(0.0),
              /* :: */[
                StyleRe.position(/* absolute */-1013592457),
                /* :: */[
                  StyleRe.widthPct(100.0),
                  /* :: */[
                    StyleRe.heightPct(100.0),
                    /* :: */[
                      StyleRe.overflow(/* hidden */-862584982),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]),
      backgroundImageWrapper: StyleRe.style(/* :: */[
            StyleRe.position(/* absolute */-1013592457),
            /* :: */[
              StyleRe.widthPct(100.0),
              /* :: */[
                StyleRe.heightPct(100.0),
                /* [] */0
              ]
            ]
          ]),
      alert: StyleRe.style(/* :: */[
            StyleRe.borderRadius(2.0),
            /* :: */[
              StyleRe.padding(15.0),
              shadow(10.0)
            ]
          ]),
      alertText: StyleRe.style(/* :: */[
            StyleRe.color("white"),
            /* :: */[
              StyleRe.backgroundColor("transparent"),
              /* [] */0
            ]
          ]),
      alertInfo: StyleRe.style(/* :: */[
            StyleRe.backgroundColor(Theme.info),
            /* [] */0
          ]),
      alertWarning: StyleRe.style(/* :: */[
            StyleRe.backgroundColor(Theme.warning),
            /* [] */0
          ]),
      alertDanger: StyleRe.style(/* :: */[
            StyleRe.backgroundColor(Theme.danger),
            /* [] */0
          ])
    });

var component = ReasonReact.statelessComponent("Text");

function make(value, $staropt$star, _children) {
  var style = $staropt$star ? $staropt$star[0] : _style;
  var styles = StyleSheetRe.flatten(/* :: */[
        stylesheet.text,
        /* :: */[
          style,
          /* [] */0
        ]
      ]);
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Curry.app(TextRe.Text[/* make */0], [
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* Some */[styles],
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* Some */[value],
                      _children
                    ]));
    });
  return newrecord;
}

var Text = /* module */[
  /* component */component,
  /* make */make
];

var component$1 = ReasonReact.statelessComponent("Btn");

function make$1($staropt$star, onPress, $staropt$star$1, children) {
  var style = $staropt$star ? $staropt$star[0] : _style;
  var theme = $staropt$star$1 ? $staropt$star$1[0] : /* default */465819841;
  var newrecord = component$1.slice();
  newrecord[/* render */9] = (function () {
      var match = +(theme === /* success */944645571);
      var styles = StyleSheetRe.flatten(/* :: */[
            stylesheet.button,
            /* :: */[
              match !== 0 ? stylesheet.buttonSuccess : _style,
              /* :: */[
                style,
                /* [] */0
              ]
            ]
          ]);
      return ReasonReact.element(/* None */0, /* None */0, TouchableOpacityRe.make(/* None */0, /* None */0, /* Some */[/* :: */[
                          /* button */-639606286,
                          /* [] */0
                        ]], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[onPress], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* Some */[styles],
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                /* None */0,
                                children
                              ]))]));
    });
  return newrecord;
}

var Btn = /* module */[
  /* component */component$1,
  /* make */make$1
];

var component$2 = ReasonReact.statelessComponent("Label");

function make$2(value, $staropt$star, _) {
  var style = $staropt$star ? $staropt$star[0] : _style;
  var newrecord = component$2.slice();
  newrecord[/* render */9] = (function () {
      var styles = StyleSheetRe.flatten(/* :: */[
            stylesheet.label,
            /* :: */[
              style,
              /* [] */0
            ]
          ]);
      return ReasonReact.element(/* None */0, /* None */0, make(value, /* Some */[styles], /* array */[]));
    });
  return newrecord;
}

var Label = /* module */[
  /* component */component$2,
  /* make */make$2
];

var component$3 = ReasonReact.statelessComponent("InputGroup");

function make$3($staropt$star, children) {
  var style = $staropt$star ? $staropt$star[0] : _style;
  var newrecord = component$3.slice();
  newrecord[/* render */9] = (function () {
      var styles = StyleSheetRe.flatten(/* :: */[
            stylesheet.inputGroup,
            /* :: */[
              style,
              /* [] */0
            ]
          ]);
      return ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* Some */[styles],
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      children
                    ]));
    });
  return newrecord;
}

var InputGroup = /* module */[
  /* component */component$3,
  /* make */make$3
];

var component$4 = ReasonReact.statelessComponent("Input");

function make$4($staropt$star, $staropt$star$1, $staropt$star$2, $staropt$star$3, $staropt$star$4, onChange, $staropt$star$5, $staropt$star$6, value, _) {
  var inputRef = $staropt$star ? $staropt$star[0] : (function () {
        return /* () */0;
      });
  var autoCapitalize = $staropt$star$1 ? $staropt$star$1[0] : /* sentences */57776752;
  var style = $staropt$star$2 ? $staropt$star$2[0] : StyleRe.style(/* [] */0);
  var keyboardType = $staropt$star$3 ? $staropt$star$3[0] : /* default */465819841;
  var secure = $staropt$star$4 ? $staropt$star$4[0] : /* false */0;
  var onSubmit = $staropt$star$5 ? $staropt$star$5[0] : (function () {
        return /* () */0;
      });
  var returnKeyType = $staropt$star$6 ? $staropt$star$6[0] : /* next */-922581773;
  var newrecord = component$4.slice();
  newrecord[/* render */9] = (function () {
      var styles = StyleSheetRe.flatten(/* :: */[
            stylesheet.textInput,
            /* :: */[
              style,
              /* [] */0
            ]
          ]);
      return ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* Some */[stylesheet.textInputWrap],
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* array */[ReasonReact.element(/* None */0, /* Some */[inputRef], TextInputRe.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[styles], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[autoCapitalize], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[keyboardType], /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[onChange], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[onSubmit], /* None */0, /* None */0, /* Some */[returnKeyType], /* Some */[secure], /* None */0, /* None */0, /* None */0, /* Some */[value], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */["transparent"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[]))]
                    ]));
    });
  return newrecord;
}

var Input = /* module */[
  /* component */component$4,
  /* make */make$4
];

var component$5 = ReasonReact.statelessComponent("Row");

function make$5($staropt$star, $staropt$star$1, $staropt$star$2, children) {
  var justifyContent = $staropt$star ? $staropt$star[0] : /* flexStart */662439529;
  var alignItems = $staropt$star$1 ? $staropt$star$1[0] : /* flexStart */662439529;
  var style = $staropt$star$2 ? $staropt$star$2[0] : StyleRe.style(/* [] */0);
  var newrecord = component$5.slice();
  newrecord[/* render */9] = (function () {
      var styles = StyleSheetRe.flatten(/* :: */[
            stylesheet.column,
            /* :: */[
              StyleRe.style(/* :: */[
                    StyleRe.justifyContent(justifyContent),
                    /* [] */0
                  ]),
              /* :: */[
                StyleRe.style(/* :: */[
                      StyleRe.alignItems(alignItems),
                      /* [] */0
                    ]),
                /* :: */[
                  style,
                  /* [] */0
                ]
              ]
            ]
          ]);
      return ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* Some */[styles],
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      children
                    ]));
    });
  return newrecord;
}

var Row = /* module */[
  /* component */component$5,
  /* make */make$5
];

var component$6 = ReasonReact.statelessComponent("Column");

function make$6($staropt$star, $staropt$star$1, $staropt$star$2, children) {
  var justifyContent = $staropt$star ? $staropt$star[0] : /* flexStart */662439529;
  var alignItems = $staropt$star$1 ? $staropt$star$1[0] : /* flexStart */662439529;
  var style = $staropt$star$2 ? $staropt$star$2[0] : StyleRe.style(/* [] */0);
  var newrecord = component$6.slice();
  newrecord[/* render */9] = (function () {
      var styles = StyleSheetRe.flatten(/* :: */[
            stylesheet.column,
            /* :: */[
              StyleRe.style(/* :: */[
                    StyleRe.justifyContent(justifyContent),
                    /* [] */0
                  ]),
              /* :: */[
                StyleRe.style(/* :: */[
                      StyleRe.alignItems(alignItems),
                      /* [] */0
                    ]),
                /* :: */[
                  style,
                  /* [] */0
                ]
              ]
            ]
          ]);
      return ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* Some */[styles],
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      children
                    ]));
    });
  return newrecord;
}

var Column = /* module */[
  /* component */component$6,
  /* make */make$6
];

var component$7 = ReasonReact.statelessComponent("Padding");

function make$7($staropt$star, children) {
  var style = $staropt$star ? $staropt$star[0] : _style;
  var newrecord = component$7.slice();
  newrecord[/* render */9] = (function () {
      var styles = StyleSheetRe.flatten(/* :: */[
            stylesheet.padding,
            /* :: */[
              style,
              /* [] */0
            ]
          ]);
      return ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* Some */[styles],
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      children
                    ]));
    });
  return newrecord;
}

var Padding = /* module */[
  /* component */component$7,
  /* make */make$7
];

var component$8 = ReasonReact.statelessComponent("BackgroundImage");

function make$8(source, $staropt$star, _) {
  var blur = $staropt$star ? $staropt$star[0] : 0.0;
  var newrecord = component$8.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* Some */[stylesheet.backgroundImageWrapper],
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* array */[ReasonReact.element(/* None */0, /* None */0, Curry.app(ImageRe.Image[/* make */3], [
                                  /* None */0,
                                  /* None */0,
                                  /* None */0,
                                  /* None */0,
                                  /* None */0,
                                  /* None */0,
                                  /* Some */[source],
                                  /* Some */[stylesheet.backgroundImage],
                                  /* None */0,
                                  /* None */0,
                                  /* None */0,
                                  /* None */0,
                                  /* Some */[blur],
                                  /* None */0,
                                  /* None */0,
                                  /* None */0,
                                  /* None */0,
                                  /* array */[]
                                ]))]
                    ]));
    });
  return newrecord;
}

var BackgroundImage = /* module */[
  /* component */component$8,
  /* make */make$8
];

var component$9 = ReasonReact.statelessComponent("Alert");

function make$9($staropt$star, $staropt$star$1, message, _) {
  var style = $staropt$star ? $staropt$star[0] : _style;
  var theme = $staropt$star$1 ? $staropt$star$1[0] : /* info */-977586066;
  var newrecord = component$9.slice();
  newrecord[/* render */9] = (function () {
      var match = +(theme === /* info */-977586066);
      var match$1 = +(theme === /* warning */164354652);
      var match$2 = +(theme === /* danger */512905955);
      var styles = StyleSheetRe.flatten(/* :: */[
            stylesheet.alert,
            /* :: */[
              match !== 0 ? stylesheet.alertInfo : _style,
              /* :: */[
                match$1 !== 0 ? stylesheet.alertWarning : _style,
                /* :: */[
                  match$2 !== 0 ? stylesheet.alertDanger : _style,
                  /* :: */[
                    style,
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]);
      return ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* Some */[styles],
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* array */[ReasonReact.element(/* None */0, /* None */0, make(message, /* Some */[stylesheet.alertText], /* array */[]))]
                    ]));
    });
  return newrecord;
}

var Alert = /* module */[
  /* component */component$9,
  /* make */make$9
];

var StyleSheet = 0;

var Style = 0;

var View = 0;

var StatusBar = 0;

var Image = 0;

var Packager = 0;

var ActivityIndicator = 0;

var TouchableOpacity = 0;

exports._style            = _style;
exports.StyleSheet        = StyleSheet;
exports.Style             = Style;
exports.View              = View;
exports.StatusBar         = StatusBar;
exports.Image             = Image;
exports.Packager          = Packager;
exports.ActivityIndicator = ActivityIndicator;
exports.TouchableOpacity  = TouchableOpacity;
exports.shadow            = shadow;
exports.stylesheet        = stylesheet;
exports.Text              = Text;
exports.Btn               = Btn;
exports.Label             = Label;
exports.InputGroup        = InputGroup;
exports.Input             = Input;
exports.Row               = Row;
exports.Column            = Column;
exports.Padding           = Padding;
exports.BackgroundImage   = BackgroundImage;
exports.Alert             = Alert;
/* _style Not a pure module */
