// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var PlatformRe = require("bs-react-native/lib/js/src/platformRe.js");

var host = PlatformRe.os !== 0 ? "http://10.0.2.2:8080" : "http://localhost:8080";

exports.host = host;
/* PlatformRe Not a pure module */
