// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';


function head(list) {
  if (list) {
    var a = list[0];
    if (list[1]) {
      return /* Some */[a];
    } else {
      return /* Some */[a];
    }
  } else {
    return /* None */0;
  }
}

function tail(list) {
  if (list) {
    var a = list[1];
    if (a) {
      return /* Some */[a];
    } else {
      return /* None */0;
    }
  } else {
    return /* None */0;
  }
}

exports.head = head;
exports.tail = tail;
/* No side effect */
