// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function encoder(errEncoder, valueEncoder, value) {
  if (typeof value === "number") {
    if (value) {
      return "Pending";
    } else {
      return "NotAsked";
    }
  } else if (value.tag) {
    return Curry._1(valueEncoder, value[0]);
  } else {
    return Curry._1(errEncoder, value[0]);
  }
}

exports.encoder = encoder;
/* No side effect */
