// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';


var grayDark = "#373a3c";

var gray = "#55595c";

var grayLight = "#818a91";

var grayLighter = "#eceeef";

var grayLightest = "#f7f7f9";

var primary = "#173236";

var secondary = "#F47627";

var success = "#77B144";

var info = "#FBC43A";

var warning = "#FBC43A";

var danger = "#F47627";

var primaryInverse = grayDark;

var inactive = "#55595c";

var paddingBase = 25;

var marginBase = 5;

var fontSize = 15;

var textColor = gray;

exports.grayDark       = grayDark;
exports.gray           = gray;
exports.grayLight      = grayLight;
exports.grayLighter    = grayLighter;
exports.grayLightest   = grayLightest;
exports.primary        = primary;
exports.secondary      = secondary;
exports.success        = success;
exports.info           = info;
exports.warning        = warning;
exports.danger         = danger;
exports.primaryInverse = primaryInverse;
exports.inactive       = inactive;
exports.paddingBase    = paddingBase;
exports.marginBase     = marginBase;
exports.fontSize       = fontSize;
exports.textColor      = textColor;
/* No side effect */
