// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var Block        = require("bs-platform/lib/js/block.js");
var Curry        = require("bs-platform/lib/js/curry.js");
var Js_exn       = require("bs-platform/lib/js/js_exn.js");
var Option       = require("./option.js");
var Json_decode  = require("bs-json/lib/js/src/json_decode.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function decode(decoder, json) {
  try {
    return /* Ok */Block.__(1, [Curry._1(decoder, json)]);
  }
  catch (raw_exn){
    var exn = Js_exn.internalToOCamlException(raw_exn);
    if (exn[0] === Js_exn.$$Error) {
      return /* Error */Block.__(0, [Option.withDefault("Could not parse JSON", Js_primitive.undefined_to_opt(exn[1].message))]);
    } else if (exn[0] === Json_decode.DecodeError) {
      return /* Error */Block.__(0, [exn[1]]);
    } else {
      throw exn;
    }
  }
}

exports.decode = decode;
/* No side effect */
